import type { DevotionPlanV2, PlanDay, DevotionPromptV2 } from "./types";

const TYPE_LABEL: Record<DevotionPromptV2["type"], string> = {
  reflection: "Reflection",
  prayer: "Prayer",
  journal: "Journal",
  practice: "Practice",
};

const roman = (n: number): string => {
  const map: Array<[number, string]> = [
    [10, "X"], [9, "IX"], [5, "V"], [4, "IV"], [1, "I"],
  ];
  let out = "";
  let r = n;
  for (const [v, s] of map) {
    while (r >= v) {
      out += s;
      r -= v;
    }
  }
  return out;
};

const promptToMarkdown = (p: DevotionPromptV2): string => {
  const cite = p.citations.map((c) => c.label).filter(Boolean).join(" · ");
  return [
    `### ${p.title}`,
    `_${TYPE_LABEL[p.type]} · ~${p.estimated_minutes} min_`,
    "",
    p.body,
    cite ? `\n> ${cite}` : "",
  ]
    .filter(Boolean)
    .join("\n");
};

const dayToMarkdown = (d: PlanDay): string => {
  return [
    `## Day ${roman(d.day_index + 1)} — ${d.theme}`,
    d.liturgical_note ? `_${d.liturgical_note}_\n` : "",
    ...d.prompts.map(promptToMarkdown),
  ]
    .filter(Boolean)
    .join("\n\n");
};

export const planToMarkdown = (plan: DevotionPlanV2): string => {
  const lead = plan.saint_matches[0]?.name;
  const header = [
    `# Sancti — ${plan.total_days}-day devotional plan`,
    lead ? `_Walking with ${lead}_` : "",
    "",
    plan.situation_summary,
  ]
    .filter(Boolean)
    .join("\n");

  const body = plan.days.map(dayToMarkdown).join("\n\n---\n\n");
  const footer = [
    "---",
    "",
    plan.teaching_authority_note,
    "",
    "Generated by Sancti — devotional reflection, not official Church teaching.",
  ].join("\n");

  return [header, "", body, "", footer].join("\n");
};
